version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_deploy:
    executor:
      name: node/default
    resource_class: small
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run deploy

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy
