version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:16
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy
